# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 11:39
from __future__ import unicode_literals

from django.db import migrations


def add_socialapp(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    Site = apps.get_model('sites', 'Site')
    db_alias = schema_editor.connection.alias
    app, created = SocialApp.objects.using(db_alias).get_or_create(
        provider='google',
        defaults={
            'name': 'Google',
            'client_id': '559124132137-h9jjj9jm7762uq7u2mn8h8dki7re28tv.apps.googleusercontent.com',
            'secret': '1iNc8DKhNXoey8jLs4y-E6MN',
        }
    )
    app.sites.add(Site.objects.get_current())


def delete_socialapp(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    db_alias = schema_editor.connection.alias
    SocialApp.objects.using(db_alias).filter(provider='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_site'),
    ]

    operations = [
        migrations.RunPython(add_socialapp, delete_socialapp),
    ]
