# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_rename_scheduled_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparkjobrun',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sparkjobrun',
            name='log_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
