sudo: required
language: python
python:
  - "2.7"
services:
  - docker
install:
  - pip install codecov
env:
  global:
    - DEBUG=False
    - SECRET_KEY=bd2b6169a99f2561168eb6b39c3fe9ad4b184a2e485781a3c875a1d1052d469d
before_script:
  - cp .env-dist .env
script:
  - make test
after_success:
  - codecov --env TRAVIS_OS_NAME
