version: '2'
services:

  db:
    image: postgres:9.4

  redis:
    image: redis:3.2

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    depends_on:
      - app
    links:
      - db
      - redis
    command: bin/run web

  worker:
    extends:
      service: app
    links:
      - db
      - redis
    command: bin/run worker

  scheduler:
    extends:
      service: app
    links:
      - db
      - redis
    # django-rq doesn't support rqscheduler `retry` mode yet
    # so we need to use the original startup script
    command: bin/run scheduler
