version: '2'

services:
  db:
    image: postgres:9.4
    ports:
      - "15432:5432"
  redis:
    image: redis:3.2

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_CONFIGURATION
    env_file:
      - .env
    volumes:
      - $PWD:/app
    command: "true"

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    command: web-dev

  worker:
    extends:
      service: app
    links:
      - db
      - redis
    command: worker

  scheduler:
    extends:
      service: app
    links:
      - db
      - redis
    command: scheduler

  monitor:
    extends:
      service: app
    links:
      - db
      - redis
    command: monitor
