version: '2'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    - DJANGO_CONFIGURATION
  env_file:
    - .env
  volumes:
    - $PWD:/app
  links:
    - db
    - redis
  command: web-dev

services:
  db:
    image: postgres:9.4
    ports:
      - "15432:5432"
  redis:
    image: redis:3.2

  web:
    <<: *app
    ports:
      - "8000:8000"

  worker:
    <<: *app
    command: worker

  scheduler:
    <<: *app
    command: scheduler

  monitor:
    <<: *app
    command: monitor
