version: '2'
services:

  db:
    image: postgres:9.4

  redis:
    image: redis:3.2

  app:
    build: .
    volumes:
      - .:/app

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    depends_on:
      - app
    links:
      - db
      - redis
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT}"

  worker:
    extends:
      service: app
    links:
      - db
      - redis
    command: python manage.py rqworker default

  scheduler:
    extends:
      service: app
    links:
      - db
      - redis
    # django-rq doesn't support rqscheduler `retry` mode yet
    # so we need to use the original startup script
    command: rqscheduler --url=${REDIS_URL}
