web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  environment:
    - DATABASE_URL=sqlite:///telemetry_analysis.db
    - PYTHONDONTWRITEBYTECODE=1
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  command:
    ./bin/run-dev.sh
