db:
  image: postgres:9.4
redis:
  image: redis:3.2
web:
  extends:
    file: docker-compose-base.yml
    service: python_base
  ports:
    - "8000:8000"
  links:
    - db
    - redis
  command:
    ./bin/run-dev.sh
rq_worker:
  extends:
    file: docker-compose-base.yml
    service: python_base
  links:
    - db
    - redis
  command:
    python manage.py rqworker default
